### ISSUE TITLE
< 100 lines

### ISSUE THREAD

**Issue by PySimpleGUI** [israel-dryer/Notepad#1]
Would it be possible to condense a bit and get it to be 99 lines or less.

It would be quite an accomplishment to be under 100 lines.  (As if it's not already a pretty fricken amazing accomplishment!)

**Comment by israel-dryer** [comment]
done.

![image](https://user-images.githubusercontent.com/42584742/66350331-0a76ce80-e929-11e9-8397-9ebf6a5d9451.png)

**Comment by PySimpleGUI** [comment]
I know it's a stupid kind of request.  Very vanity kind of thing. 

But it just sounds awesome and unbelievable especially since it's portable and doesn't require some fancy Qt widget that will do it all for you, but is impossible to configure.

**Comment by israel-dryer** [comment]
Not a problem. Part of getting out the word about PySimpleGUI is being able to have a selling point, and fewer lines of code is definitely one of them. I've seen this same program with way more lines and  far fewer features from a vanilla tkinter implementation.

I know this isn't super fancy, like the code-editor version, but it's definitely something that would be easy for a beginner to get their head around, and without the extra tkinter customizations.

**Comment by PySimpleGUI** [comment]
Yea, I spend a lot of time on sales and marketing.  People hate it, but it's what you have to do if you want your "product" to be used.  You've got to sell it.

I eventually want to see this get in front of Guido.  I want his opinion.

I think that I've accidentally discovered THE GUI model for Python.  This is by far the best fit for the language that I've ever seen.

I think the biggest test for this is the ability to use a list comprehension to build the GUI layout.  Also that lists are used everywhere from the layout to the menus.  

It's a real mystery why the OO design has stuck so strongly with the GUI packages for Python when they are some of the most difficult architectures to work with in Python.  

Simple GUIs should be simple to make.  Just like EVERYTHING else in Python.  That's what's amazing about this language.  But also, Complex things should be... simple to make.  You've been making really complex things, but they're done in a really simple way that can be easily broken down and understood.

I dunno, maybe he won't agree, but it would be nice to get his opinion.
