### ISSUE TITLE
Question about key codes for ctrl+<some_key> combination

### ISSUE THREAD

**Issue by barokimPL** [israel-dryer/Notepad#3]
Hi, I'm trying to add some keyboard shortcuts to my PySimpleGUI program, but I can't find a way to capture events consisting of ctrl+<some_key>. Just capturing all events and printing them yields only single keystrokes. I can see though that you made it work using some sort of codes - where did you get them from? They're working for me too, and I'd love the whole table!

Example from your program that works for me to: 

```
if event in ('New (Ctrl+N)', 'n:78'):
    file = new_file()
```

**Comment by israel-dryer** [comment]
PySimpleGUI keyboard events are kind of strange to be honest. It has a different event mechanism than the underlying tkinter it wraps. So, what I do is simply press the keys to see what event(s) is being returned. The **<Ctrl+Key>** events are returned in multiples... one is the combo event you are looking for, and the others are just the **<KeyUp>** event of one or both of the other two keys as you release them.   

For example, pressing **<Ctrl+c>** produces `c:67`,  which is the combo event. However, you might also get `Control_L:17`, which is the control key event. Depending on the order or speed at which you release the keys, you may also get a `c` event.

**Comment by barokimPL** [comment]
Came up with something similar, but it didn't work with BackSpace (it always shows BackSpace:8, even without modifier) so I hoped you found something I didn't. Thanks for the reply though, cheers!
